// The iris bundle (apps/viewer/public/bundles/iris.json, generated by
// tools/iris/train.py) evaluated by Tensatory's net evaluator must agree with
// PyTorch evaluating the same weights at the same displaced points
// (packages/core/test/fixtures/iris-reference.json, float64 in both).

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { Bundle, DenseGrid, NdArray, SymbolicScalarFieldData, SymbolicVectorFieldData } from "../src";

const bundle = Bundle.parse(JSON.parse(readFileSync(join(__dirname, "../../../apps/viewer/public/bundles/iris.json"), "utf8")));
// the viewer's fields use random directions (iris_rnd2 / iris_rnd3, drawn from seeds); the PyTorch reference was
// computed along the fixed inline directions kept in iris_rand2 / iris_rand3, so give those fields of their own
const refFields = (net: string, dims: number) => ({
  loss: { kind: "scalar", codomain: "celoss", domain: `rand${dims}`, data: { type: "net", net, output: "loss", box: Array.from({ length: dims }, () => [-1, 1]) } },
  acc: { kind: "scalar", codomain: "fraction", domain: `rand${dims}`, data: { type: "net", net, output: "acc", box: Array.from({ length: dims }, () => [-1, 1]) } },
});
const reference = new Bundle({ ...bundle.spec, fields: { ...bundle.spec.fields, ...Object.fromEntries(Object.entries(refFields("iris_rand2", 2)).map(([k, v]) => [`${k}2`, v])), ...Object.fromEntries(Object.entries(refFields("iris_rand3", 3)).map(([k, v]) => [`${k}3`, v])) } } as typeof bundle.spec);
const ref = JSON.parse(readFileSync(join(__dirname, "fixtures/iris-reference.json"), "utf8")) as {
  points2: number[][]; loss2: number[]; acc2: number[];
  points3: number[][]; loss3: number[]; acc3: number[];
};

describe("iris bundle vs PyTorch", () => {
  it("builds every net and field", () => {
    expect([...bundle.buildAll().entries()].map(([id, e]) => `${id}: ${e.message}`)).toEqual([]);
    expect(bundle.net("iris_star").signature.inputs).toEqual({});
    expect(bundle.net("iris_rand2").signature.inputs).toEqual({ t: [2] });
    expect(bundle.net("iris_rand3").signature.inputs).toEqual({ t: [3] });
    expect(bundle.net("iris_rnd2").signature.inputs).toEqual({ t: [2] });
    expect(bundle.net("iris_rnd3").signature.inputs).toEqual({ t: [3] });
  });

  it("the random directions are as long as θ* and d₀ / d₁ are the same draws in both spaces", () => {
    const norm = (xs: ArrayLike<number>) => { let s = 0; for (let i = 0; i < xs.length; i++) s += xs[i]! * xs[i]!; return Math.sqrt(s); };
    const star = bundle.net("iris_star").program;
    const thetaNorm = norm(Float64Array.from(["W1", "b1", "W2", "b2"].flatMap((a) => Array.from(star.consts[a]!.arr.data))));
    const p2 = bundle.net("iris_rnd2").program, p3 = bundle.net("iris_rnd3").program;
    for (const [prog, K] of [[p2, 2], [p3, 3]] as const) {
      for (let k = 0; k < K; k++) {
        const dk = Float64Array.from(["W1", "b1", "W2", "b2"].flatMap((a) => { const c = prog.consts[`${a}__dispd`]!; const n = c.arr.size / K; return Array.from(c.arr.data.subarray(k * n, (k + 1) * n)); }));
        expect(norm(dk)).toBeCloseTo(thetaNorm, 9);
      }
    }
    for (const a of ["W1", "b1", "W2", "b2"]) {
      const c2 = p2.consts[`${a}__dispd`]!.arr, c3 = p3.consts[`${a}__dispd`]!.arr;
      expect(Array.from(c3.data.subarray(0, c2.size))).toEqual(Array.from(c2.data));
    }
  });

  it("loss and accuracy at θ* match PyTorch", () => {
    const out = bundle.net("iris_star").evaluate({});
    expect(out.loss!.data[0]).toBeCloseTo(ref.loss2[0]!, 10);
    expect(out.acc!.data[0]).toBeCloseTo(ref.acc2[0]!, 12);
    expect([...out.logits!.shape]).toEqual([30, 3]);
  });

  it("loss and accuracy along 2 and 3 random directions match PyTorch (field evaluation)", () => {
    const loss2 = reference.scalarField("loss2").data, acc2 = reference.scalarField("acc2").data;
    ref.points2.forEach((p, i) => {
      expect(loss2.value(p), `loss2 at ${p}`).toBeCloseTo(ref.loss2[i]!, 9);
      expect(acc2.value(p), `acc2 at ${p}`).toBeCloseTo(ref.acc2[i]!, 12);
    });
    const loss3 = reference.scalarField("loss3").data, acc3 = reference.scalarField("acc3").data;
    ref.points3.forEach((p, i) => {
      expect(loss3.value(p), `loss3 at ${p}`).toBeCloseTo(ref.loss3[i]!, 9);
      expect(acc3.value(p), `acc3 at ${p}`).toBeCloseTo(ref.acc3[i]!, 12);
    });
  });

  it("batched evaluation of the displaced net equals the reference (all points in one call)", () => {
    const t = new NdArray([ref.points3.length, 3], Float64Array.from(ref.points3.flat()));
    const out = bundle.net("iris_rand3").evaluate({ t });
    expect([...out.loss!.shape]).toEqual([ref.points3.length]);
    ref.loss3.forEach((l, i) => expect(out.loss!.data[i]).toBeCloseTo(l, 9));
    ref.acc3.forEach((a, i) => expect(out.acc!.data[i]).toBeCloseTo(a, 12));
  });

  it("grid sampling is the batched evaluation, and is reasonably fast", () => {
    const loss2 = bundle.scalarField("loss2").data;
    const grid = new DenseGrid([64, 64], loss2.box);
    const t0 = performance.now();
    const vals = loss2.sampleOn(grid);
    const ms = performance.now() - t0;
    const p = new Float64Array(2);
    for (const i of [0, 777, 2048, 4095]) { grid.pointInto(i, p); expect(vals[i]).toBeCloseTo(loss2.fn(p, -1), 10); }
    // θ* is a low point of the landscape (not necessarily the minimum along random directions: weight decay)
    let best = 0;
    for (let i = 1; i < vals.length; i++) if (vals[i]! < vals[best]!) best = i;
    expect(vals[best]).toBeLessThanOrEqual(ref.loss2[0]!);
    expect(vals[best]).toBeGreaterThan(0.5 * ref.loss2[0]!);
    expect(ms, `64x64 grid took ${ms.toFixed(0)} ms`).toBeLessThan(1000);
  });
});

describe("costly fields", () => {
  it("net fields and everything derived from them report costly; cheap fields do not", () => {
    const loss = bundle.scalarField("loss2").data;
    expect(loss.costly).toBe(true);
    expect(loss.derivative(0).costly).toBe(true);
    const grad = new SymbolicVectorFieldData({ k: "grad", s: { k: "arg", name: "f" } }, 2, { scalars: { f: loss }, vectors: {} });
    expect(grad.costly).toBe(true);
    expect(grad.component(1).costly).toBe(true);
    expect(new SymbolicScalarFieldData({ k: "coord", index: 0 }, 2).costly).toBe(false);
  });

  it("the gradient use sampled on a grid is batched and equals the per-point evaluation", () => {
    const loss = bundle.scalarField("loss3").data;
    const grad = new SymbolicVectorFieldData({ k: "grad", s: { k: "arg", name: "f" } }, 3, { scalars: { f: loss }, vectors: {} });
    const grid = new DenseGrid([12, 12, 12], loss.box);
    const t0 = performance.now();
    const vals = grad.sampleOn(grid);
    const ms = performance.now() - t0;
    const p = new Float64Array(3), v = new Float64Array(3);
    for (const i of [0, 100, 1000, 1727]) {
      grid.pointInto(i, p); grad.fn(p, -1, v);
      for (let d = 0; d < 3; d++) expect(vals[3 * i + d]).toBeCloseTo(v[d]!, 9);
    }
    expect(ms, `12³ gradient grid took ${ms.toFixed(0)} ms`).toBeLessThan(1500);
  });
});
