// The iris bundle (apps/viewer/public/bundles/iris.json, generated by
// tools/iris/train.py) evaluated by Tensatory's net evaluator must agree with
// PyTorch evaluating the same weights at the same displaced points
// (packages/core/test/fixtures/iris-reference.json, float64 in both).

import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { Bundle, DenseGrid, NdArray, SymbolicScalarFieldData, SymbolicVectorFieldData } from "../src";

const bundle = Bundle.parse(JSON.parse(readFileSync(join(__dirname, "../../../apps/viewer/public/bundles/iris.json"), "utf8")));
const ref = JSON.parse(readFileSync(join(__dirname, "fixtures/iris-reference.json"), "utf8")) as {
  points2: number[][]; loss2: number[]; acc2: number[];
  points3: number[][]; loss3: number[]; acc3: number[];
};

describe("iris bundle vs PyTorch", () => {
  it("builds every net and field", () => {
    expect([...bundle.buildAll().entries()].map(([id, e]) => `${id}: ${e.message}`)).toEqual([]);
    expect(bundle.net("iris_star").signature.inputs).toEqual({});
    expect(bundle.net("iris_rand2").signature.inputs).toEqual({ t: [2] });
    expect(bundle.net("iris_rand3").signature.inputs).toEqual({ t: [3] });
  });

  it("loss and accuracy at θ* match PyTorch", () => {
    const out = bundle.net("iris_star").evaluate({});
    expect(out.loss!.data[0]).toBeCloseTo(ref.loss2[0]!, 10);
    expect(out.acc!.data[0]).toBeCloseTo(ref.acc2[0]!, 12);
    expect([...out.logits!.shape]).toEqual([30, 3]);
  });

  it("loss and accuracy along 2 and 3 random directions match PyTorch (field evaluation)", () => {
    const loss2 = bundle.scalarField("loss2").data, acc2 = bundle.scalarField("acc2").data;
    ref.points2.forEach((p, i) => {
      expect(loss2.value(p), `loss2 at ${p}`).toBeCloseTo(ref.loss2[i]!, 9);
      expect(acc2.value(p), `acc2 at ${p}`).toBeCloseTo(ref.acc2[i]!, 12);
    });
    const loss3 = bundle.scalarField("loss3").data, acc3 = bundle.scalarField("acc3").data;
    ref.points3.forEach((p, i) => {
      expect(loss3.value(p), `loss3 at ${p}`).toBeCloseTo(ref.loss3[i]!, 9);
      expect(acc3.value(p), `acc3 at ${p}`).toBeCloseTo(ref.acc3[i]!, 12);
    });
  });

  it("batched evaluation of the displaced net equals the reference (all points in one call)", () => {
    const t = new NdArray([ref.points3.length, 3], Float64Array.from(ref.points3.flat()));
    const out = bundle.net("iris_rand3").evaluate({ t });
    expect([...out.loss!.shape]).toEqual([ref.points3.length]);
    ref.loss3.forEach((l, i) => expect(out.loss!.data[i]).toBeCloseTo(l, 9));
    ref.acc3.forEach((a, i) => expect(out.acc!.data[i]).toBeCloseTo(a, 12));
  });

  it("grid sampling is the batched evaluation, and is reasonably fast", () => {
    const loss2 = bundle.scalarField("loss2").data;
    const grid = new DenseGrid([64, 64], loss2.box);
    const t0 = performance.now();
    const vals = loss2.sampleOn(grid);
    const ms = performance.now() - t0;
    const p = new Float64Array(2);
    for (const i of [0, 777, 2048, 4095]) { grid.pointInto(i, p); expect(vals[i]).toBeCloseTo(loss2.fn(p, -1), 10); }
    // θ* is a low point of the landscape (not necessarily the minimum along random directions: weight decay)
    let best = 0;
    for (let i = 1; i < vals.length; i++) if (vals[i]! < vals[best]!) best = i;
    expect(vals[best]).toBeLessThanOrEqual(ref.loss2[0]!);
    expect(vals[best]).toBeGreaterThan(0.5 * ref.loss2[0]!);
    expect(ms, `64x64 grid took ${ms.toFixed(0)} ms`).toBeLessThan(1000);
  });
});

describe("costly fields", () => {
  it("net fields and everything derived from them report costly; cheap fields do not", () => {
    const loss = bundle.scalarField("loss2").data;
    expect(loss.costly).toBe(true);
    expect(loss.derivative(0).costly).toBe(true);
    const grad = new SymbolicVectorFieldData({ k: "grad", s: { k: "arg", name: "f" } }, 2, { scalars: { f: loss }, vectors: {} });
    expect(grad.costly).toBe(true);
    expect(grad.component(1).costly).toBe(true);
    expect(new SymbolicScalarFieldData({ k: "coord", index: 0 }, 2).costly).toBe(false);
  });

  it("the gradient use sampled on a grid is batched and equals the per-point evaluation", () => {
    const loss = bundle.scalarField("loss3").data;
    const grad = new SymbolicVectorFieldData({ k: "grad", s: { k: "arg", name: "f" } }, 3, { scalars: { f: loss }, vectors: {} });
    const grid = new DenseGrid([12, 12, 12], loss.box);
    const t0 = performance.now();
    const vals = grad.sampleOn(grid);
    const ms = performance.now() - t0;
    const p = new Float64Array(3), v = new Float64Array(3);
    for (const i of [0, 100, 1000, 1727]) {
      grid.pointInto(i, p); grad.fn(p, -1, v);
      for (let d = 0; d < 3; d++) expect(vals[3 * i + d]).toBeCloseTo(v[d]!, 9);
    }
    expect(ms, `12³ gradient grid took ${ms.toFixed(0)} ms`).toBeLessThan(1500);
  });
});
