// The MNIST MLP bundle (apps/viewer/public/bundles/mnist-mlp/, generated by tools/mnist/export.py from the
// loss-landscape prototype's checkpoint) evaluated by Tensatory's net evaluator must agree with PyTorch on the same
// float32 weights at the same displaced points (fixtures/mnist-mlp-reference.json). This is the first bundle whose
// arrays all come from .npz members through the handle backend, at real sizes (269k weights, 1024 × 784 uint8).

import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { Bundle } from "../src";
import { dirSource } from "./helpers";

const DIR = join(__dirname, "../../../apps/viewer/public/bundles/mnist-mlp");
const src = dirSource(DIR);
type Ref = { loss: number; acc: number };
const refP = readFile(join(__dirname, "fixtures/mnist-mlp-reference.json"), "utf8").then((s) => JSON.parse(s) as {
  eval_n: number; small_n: number; points3: number[][]; points2: number[][];
  full3: Ref[]; full2: Ref[]; small3: Ref[]; small2: Ref[];
});
const bundleP = readFile(join(DIR, "bundle.json"), "utf8").then((s) => Bundle.load(JSON.parse(s), src));

describe("MNIST MLP bundle vs PyTorch", () => {
  it("loads every .npz member and builds every net and field", async () => {
    const b = await bundleP;
    expect([...b.buildAll().entries()].map(([id, e]) => `${id}: ${e.message}`)).toEqual([]);
    expect(b.net("mlp_star").signature.inputs).toEqual({});
    expect(b.net("mlp_pca3").signature.inputs).toEqual({ t: [3] });
    const x = b.arrays.raw("arrays.npz/data/x", []);
    expect(x.shape).toEqual([1024, 784]);
    expect(x.data).toBeInstanceOf(Uint8Array); // pixels stay 1 byte each; the net normalizes
    expect(b.arrays.raw("arrays.npz/theta/W1t", []).data).toBeInstanceOf(Float32Array);
  }, 60_000);

  it("the 256-example fields agree with PyTorch at θ* and at displaced points (2D and 3D)", async () => {
    const [b, ref] = await Promise.all([bundleP, refP]);
    const loss2 = b.scalarField("fastLoss2").data, acc2 = b.scalarField("fastAcc2").data;
    const loss3 = b.scalarField("fastLoss3").data, acc3 = b.scalarField("fastAcc3").data;
    ref.points2.forEach((p, i) => {
      expect(loss2.value(p)).toBeCloseTo(ref.small2[i]!.loss, 6);
      expect(acc2.value(p)).toBeCloseTo(ref.small2[i]!.acc, 9);
    });
    ref.points3.forEach((p, i) => {
      expect(loss3.value(p)).toBeCloseTo(ref.small3[i]!.loss, 6);
      expect(acc3.value(p)).toBeCloseTo(ref.small3[i]!.acc, 9);
    });
  }, 120_000);

  it("the 1024-example loss agrees with PyTorch at θ* and one displaced point", async () => {
    const [b, ref] = await Promise.all([bundleP, refP]);
    const loss3 = b.scalarField("loss3").data, acc3 = b.scalarField("acc3").data;
    for (const i of [0, 1]) {
      expect(loss3.value(ref.points3[i]!)).toBeCloseTo(ref.full3[i]!.loss, 6);
      expect(acc3.value(ref.points3[i]!)).toBeCloseTo(ref.full3[i]!.acc, 9);
    }
  }, 120_000);

  it("the sampled prototype volume and the live net agree at θ* to the volume's own precision", async () => {
    const [b, ref] = await Promise.all([bundleP, refP]);
    const sampled = b.scalarField("sampledLog10Loss").data;
    // trilinear interpolation of a 32³ grid at the origin vs the exact live value: the grid is coarse, so loosely
    expect(sampled.value([0, 0, 0])).toBeCloseTo(Math.log10(ref.full3[0]!.loss), 1);
    expect(b.scalarField("sampledAcc").data.value([0, 0, 0])).toBeCloseTo(ref.full3[0]!.acc, 1);
  }, 60_000);
});
