// Builds apps/viewer/public/bundles/symbolic-nd.json: symbolic fields on 4D and 5D manifolds, to exercise the
// viewer's `slice` row (an N-D space is shown as an axis-aligned 2D / 3D slice through the manifold's `origin`).
//
//   node tools/symbolic-nd/build.mjs
//
// Spaces
//   gauss4    a 4D Gaussian with a full (non-diagonal) covariance, its exact gradient, |∇| and the log-density (a
//             quadratic form): slices through the peak show tilted ellipsoids; slices along other origins, off-peak
//             tails. Nothing here is separable, so every pair / triple of axes gives a different picture.
//   quad4     an indefinite quadratic form x·A·x with eigenvalues (+, +, −, −) after a rotation: a 4D saddle whose
//             2D / 3D slices are bowls, saddles or hyperbolic sheets depending on the axes chosen.
//   mix5      a 5D mixture of three Gaussians with different widths, `origin` at the mean of the second component
//             (so the default slice x₁x₂x₃ passes through that peak, not through the first), and its |∇|.
//   rosen5    the 5D Rosenbrock function Σ 100 (x_{i+1} − x_i²)² + (1 − x_i)², origin at its minimum (1, …, 1), with
//             its gradient; a log codomain.
//   waves5    Σ_i sin(x_i) + ½ Σ_i sin(x_i x_{i+1}): a periodic landscape with coupled axes.

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const X = (i) => ({ op: "coord", index: i });
const add = (...vals) => ({ op: "add", vals });
const mul = (...vals) => ({ op: "mul", vals });
const sub = (a, b) => ({ op: "sub", vals: [a, b] });
const un = (op) => (val) => ({ op, val });
const sq = un("square"), sin = un("sin"), exp = un("exp"), neg = un("negate"), log = un("log");
const grad = (val) => ({ op: "grad", val });
const norm = (vec) => ({ op: "norm", vec });
const range = (n) => Array.from({ length: n }, (_, i) => i);
/** x·A·x for a symmetric matrix A (array of rows) about a centre c */
const quadForm = (A, c = null) => {
  const d = (i) => (c ? sub(X(i), c[i]) : X(i));
  const terms = [];
  A.forEach((row, i) => row.forEach((a, j) => { if (a !== 0) terms.push(mul(a, d(i), d(j))); }));
  return add(...terms);
};
const round = (x) => +x.toPrecision(6);
/** the matrix Q diag(λ) Qᵀ for a rotation Q built from Givens rotations by `angles` [[i, j, θ], …] */
function rotated(lambda, angles) {
  const n = lambda.length;
  let Q = range(n).map((i) => range(n).map((j) => (i === j ? 1 : 0)));
  for (const [i, j, th] of angles) {
    const G = range(n).map((r) => range(n).map((c) => (r === c ? 1 : 0)));
    G[i][i] = Math.cos(th); G[j][j] = Math.cos(th); G[i][j] = -Math.sin(th); G[j][i] = Math.sin(th);
    Q = Q.map((row) => range(n).map((c) => row.reduce((s, v, k) => s + v * G[k][c], 0)));
  }
  return range(n).map((i) => range(n).map((j) => round(range(n).reduce((s, k) => s + Q[i][k] * lambda[k] * Q[j][k], 0))));
}

const bundle = {
  tensatory: "0.1",
  name: "symbolic N-D",
  summary: "Symbolic fields on 4D and 5D spaces — Gaussians, quadratic forms, Rosenbrock, waves — viewed through 2D / 3D slices (the slice row of the bundle panel).",
  details:
    "Fields defined by expressions on 4- and 5-dimensional manifolds. The viewer cannot draw four dimensions, so each space is shown as an axis-aligned 2D or 3D SLICE through the manifold's `origin`: pick the axes in the bundle panel's slice row (2 or 3 of them) and commit with the tick. " +
    "Everything downstream — colour, isolines / isosurfaces, streamlines, glyphs, exact gradients, |∇| — is computed for the N-D field restricted to that slice (|∇f| keeps all N components; a vector field shows its components along the slice). " +
    "Generated by tools/symbolic-nd/build.mjs.",
  manifolds: {},
  fields: {},
  pointSets: {},
};
const space = (id, m) => { bundle.manifolds[id] = m; };
const field = (id, f) => { bundle.fields[id] = f; };
const names = (n) => range(n).map((i) => `x${"₁₂₃₄₅₆₇₈"[i]}`);

/* ---- gauss4 ---- */
{
  const D = 4, box = range(D).map(() => [-3, 3]);
  const A = rotated([1, 0.5, 2, 0.25], [[0, 1, 0.5], [1, 2, 0.8], [2, 3, 0.4], [0, 3, 0.3]]); // precision matrix Σ⁻¹
  space("gauss4", { name: "4D Gaussian", numDims: D, dimNames: names(D), summary: "one Gaussian with a full 4×4 covariance: every 2D slice an ellipse, every 3D slice an ellipsoid, all tilted", details: `Density ∝ exp(−½ x·Λ·x) with precision matrix Λ = Q diag(1, ½, 2, ¼) Qᵀ for a rotation Q of four Givens angles. The origin (0, 0, 0, 0) is the peak, so every slice through it cuts the ellipsoid through its centre. Λ = ${JSON.stringify(A)}.` });
  const logp = mul(-0.5, quadForm(A));
  field("gauss4/p", { kind: "scalar", domain: "gauss4", name: "p", codomain: "p", summary: "exp(−½ x·Λ·x): the (unnormalized) Gaussian density", data: { type: "symbolic", box, expr: exp(logp) } });
  field("gauss4/logp", { kind: "scalar", domain: "gauss4", name: "log p", codomain: { max: 0 }, summary: "−½ x·Λ·x: the log density, a negative definite quadratic form", data: { type: "symbolic", box, expr: logp } });
  field("gauss4/grad", { kind: "vector", domain: "gauss4", name: "∇p", summary: "the exact 4D gradient of p; a slice shows its components along the slice", data: { type: "pointwisev", expr: grad("p"), scalars: { p: "gauss4/p" } } });
  field("gauss4/gradnorm", { kind: "scalar", domain: "gauss4", name: "|∇p|", codomain: "norm", summary: "the norm of the FULL 4D gradient (all four components, also on a slice)", data: { type: "pointwise", expr: norm(grad("p")), scalars: { p: "gauss4/p" } } });
  bundle.pointSets["gauss4/peak"] = { domain: "gauss4", points: [[0, 0, 0, 0]], labels: ["peak"] };
}

/* ---- quad4 ---- */
{
  const D = 4, box = range(D).map(() => [-2, 2]);
  const A = rotated([1, 0.6, -0.8, -1.2], [[0, 2, 0.6], [1, 3, 0.9], [0, 1, 0.35]]);
  space("quad4", { name: "4D indefinite quadratic", numDims: D, dimNames: names(D), summary: "x·A·x with eigenvalues (1, 0.6, −0.8, −1.2) after a rotation: a 4D saddle — slices are bowls, saddles or hyperbolic sheets by the axes chosen", details: `f = x·A·x, A = Q diag(1, 0.6, −0.8, −1.2) Qᵀ. Its level set f = 0 is a cone; a 3D slice through the origin cuts it in a double cone or in nothing, depending on the signature of the restricted form. ∇f = 2Ax is a linear vector field: the origin is a saddle of the gradient flow. A = ${JSON.stringify(A)}.` });
  field("quad4/f", { kind: "scalar", domain: "quad4", name: "f", summary: "x·A·x", data: { type: "symbolic", box, expr: quadForm(A) } });
  field("quad4/grad", { kind: "vector", domain: "quad4", name: "∇f", summary: "2Ax: a linear field, a saddle at the origin", data: { type: "pointwisev", expr: grad("f"), scalars: { f: "quad4/f" } } });
  field("quad4/gradnorm", { kind: "scalar", domain: "quad4", name: "|∇f|", codomain: "norm", summary: "|2Ax|, the full 4D norm", data: { type: "pointwise", expr: norm(grad("f")), scalars: { f: "quad4/f" } } });
  bundle.pointSets["quad4/saddle"] = { domain: "quad4", points: [[0, 0, 0, 0]], labels: ["saddle"] };
}

/* ---- mix5 ---- */
{
  const D = 5, box = range(D).map(() => [-3, 3]);
  const comps = [
    { w: 1, mu: [-1, -0.5, 0.8, 0, 0.4], s: 0.9 },
    { w: 0.7, mu: [1.2, 1, -0.6, 0.5, -1], s: 0.7 },
    { w: 0.5, mu: [0.5, -1.8, 1.5, -1.2, 1.4], s: 0.5 },
  ];
  const gk = (mu, s) => ({ op: "gaussKernel", val: norm({ op: "subv", vecs: [{ op: "coordv" }, { op: "constv", value: mu }] }), mu: 0, sigma: s });
  space("mix5", { name: "5D Gaussian mixture", numDims: D, dimNames: names(D), origin: comps[1].mu, summary: "three isotropic Gaussians of different widths in 5D; the origin sits at the SECOND component's mean, so the default slice cuts through that peak", details: `Σ wᵢ exp(−|x − μᵢ|² / 2σᵢ²) with (w, σ) = (1, 0.9), (0.7, 0.7), (0.5, 0.5). Slices pass through μ₂ = (${comps[1].mu.join(", ")}); the other peaks lie off most slices and appear as faint tails. Point set: the three means (their shadows on the slice).` });
  field("mix5/p", { kind: "scalar", domain: "mix5", name: "mixture", codomain: "p", summary: "the mixture density (peak 1 at μ₁)", data: { type: "symbolic", box, expr: { op: "clamp", min: 0, max: 1, val: add(...comps.map((c) => mul(c.w, gk(c.mu, c.s)))) } } });
  field("mix5/gradnorm", { kind: "scalar", domain: "mix5", name: "|∇ mixture|", codomain: "norm", summary: "the norm of the full 5D gradient", data: { type: "pointwise", expr: norm(grad("m")), scalars: { m: "mix5/p" } } });
  field("mix5/grad", { kind: "vector", domain: "mix5", name: "∇ mixture", summary: "the exact 5D gradient, projected onto the slice", data: { type: "pointwisev", expr: grad("m"), scalars: { m: "mix5/p" } } });
  bundle.pointSets["mix5/means"] = { domain: "mix5", points: comps.map((c) => c.mu), labels: ["μ₁", "μ₂", "μ₃"] };
}

/* ---- rosen5 ---- */
{
  const D = 5, box = range(D).map(() => [-2, 2]);
  const terms = [];
  for (let i = 0; i < D - 1; i++) terms.push(mul(100, sq(sub(X(i + 1), sq(X(i))))), sq(sub(1, X(i))));
  space("rosen5", { name: "5D Rosenbrock", numDims: D, dimNames: names(D), origin: [1, 1, 1, 1, 1], summary: "Σ 100 (x_{i+1} − x_i²)² + (1 − x_i)², origin at the minimum (1, …, 1): every slice shows the curved valley through it", details: "The chained Rosenbrock function: consecutive axes are coupled, non-consecutive ones only through the chain. A slice along (x₁, x₂) shows the classic banana; along (x₁, x₃) the valley is a parabola-free bowl-like trough; 3D slices show the valley as a tube. Log codomain." });
  field("rosen5/f", { kind: "scalar", domain: "rosen5", name: "Rosenbrock", codomain: "log", summary: "Σ 100 (x_{i+1} − x_i²)² + (1 − x_i)²", data: { type: "symbolic", box, expr: add(...terms) } });
  field("rosen5/grad", { kind: "vector", domain: "rosen5", name: "∇ Rosenbrock", summary: "the exact 5D gradient along the slice", data: { type: "pointwisev", expr: grad("f"), scalars: { f: "rosen5/f" } } });
  field("rosen5/loggradnorm", { kind: "scalar", domain: "rosen5", name: "log |∇|", summary: "log of the full 5D gradient norm (deep valley floor, steep walls)", data: { type: "pointwise", expr: log(add(1e-9, norm(grad("f")))), scalars: { f: "rosen5/f" } } });
  bundle.pointSets["rosen5/min"] = { domain: "rosen5", points: [[1, 1, 1, 1, 1]], labels: ["minimum"] };
}

/* ---- waves5 ---- */
{
  const D = 5, box = range(D).map(() => [-Math.PI, Math.PI]);
  const terms = range(D).map((i) => sin(X(i)));
  for (let i = 0; i < D - 1; i++) terms.push(mul(0.5, sin(mul(X(i), X(i + 1)))));
  space("waves5", { name: "5D waves", numDims: D, dimNames: names(D), summary: "Σ sin xᵢ + ½ Σ sin(xᵢ xᵢ₊₁) on [−π, π]⁵: a periodic landscape whose coupling terms bend the ridges", details: "Separable sines give a lattice of maxima, minima and saddles; the products xᵢxᵢ₊₁ inside the second sum couple neighbouring axes, so slices along consecutive axes show bent ridges while (x₁, x₃) slices stay square." });
  field("waves5/f", { kind: "scalar", domain: "waves5", name: "waves", codomain: "similarity", summary: "Σ sin xᵢ + ½ Σ sin(xᵢ xᵢ₊₁)", data: { type: "symbolic", box, expr: add(...terms) } });
  field("waves5/grad", { kind: "vector", domain: "waves5", name: "∇ waves", data: { type: "pointwisev", expr: grad("f"), scalars: { f: "waves5/f" } } });
  field("waves5/neg", { kind: "vector", domain: "waves5", name: "−∇ waves (descent flow)", summary: "the gradient descent flow, projected onto the slice", data: { type: "pointwisev", expr: { op: "scalev", vec: grad("f"), by: -1 }, scalars: { f: "waves5/f" } } });
  bundle.manifolds.waves5.flow = "waves5/neg";
}

const out = join(dirname(fileURLToPath(import.meta.url)), "../../apps/viewer/public/bundles/symbolic-nd.json");
writeFileSync(out, JSON.stringify(bundle, null, 1) + "\n");
console.log(`wrote ${out}: ${Object.keys(bundle.manifolds).length} spaces, ${Object.keys(bundle.fields).length} fields`);
